MM-29867: Commands to generate test data
mattermost/mattermost-plugin-incident-management pull request #358
Opened 2020-10-27 08:22 UTC by agarciamontoro

#### Summary
This PR adds two new slash commands:
- `/incident test create-incident`, which accepts a playbook ID (that can be chosen from the playbooks the user is a member of, using the autocomplete system), a timestamp and an incident name. It creates an ongoing incident whose creation date is set to the specified timestamp.
- `/incident test bulk-data`, which accepts a number of ongoing incidents, a number of ended incidents, a begin and an end date, and an optional seed. It creates as many ongoing and ended incidents as specified, all of them with their creation date randomly picked between the begin and end dates. The seed, if available, is used to get reproducible results. The names of the incidents are randomly chosen from a list of incident names and a list of fake company names I defined in the code.

Other things I did while I was here:
- I fixed the `sqlstore.NukeDB` function, which failed with a foreign key error when trying to delete `IR_Playbook` before
`IR_PlaybookMember`.
- I moved the `st` command as a subcommand of `/incident test`, for the sake of consistency.
- I excluded `G404: Insecure random number source (rand)` rule from [gosec](https://github.com/securego/gosec): it was complaining because I am using `math/rand` instead of `crpyto/rand` to generate the random numbers needed in the bulk data generation. Of course, we do not need `crypto/rand` for such a task. And, if we ever need to do something crypto-related, I think we will know by ourselves that we need to use `crypto/rand`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29867

2020-10-27 08:23 UTC, agarciamontoro commented
E2E tests are failing in CI but not locally. I'll investigate.

2020-10-28 16:49 UTC, crspeller requested changes

2020-10-28 16:49 UTC, crspeller commented on server/api/playbooks.go
> +func (h *PlaybookHandler) getPlaybooksAutoComplete(w http.ResponseWriter, r *http.Request) {
I think this needs a permission check.

2020-10-28 16:49 UTC, crspeller commented on server/incident/incident.go
> +	ChangeCreationDate(incidentID string, creationTimestamp time.Time) error
Seems like a strange function to have. Maybe a function to create with a specific timestamp would make more sense? 0/5 probably fine as is.

2020-10-29 13:44 UTC, itao commented
@agarciamontoro Could you request review from @muratbayan and @sadohert as they'll be using it in the field?

2020-10-29 13:45 UTC, itao approved these changes

2020-11-04 17:38 UTC, agarciamontoro commented on server/incident/incident.go
> +	ChangeCreationDate(incidentID string, creationTimestamp time.Time) error
I'd argue that they are equally weird, actually. The only reason I did it this way was to separate both calls, so there is only one way of creating an incident. As we're both 0/5 on this, I'll leave it as it is just not to add any more work (even if it's negligible).

2020-11-04 17:38 UTC, agarciamontoro commented on server/api/playbooks.go
> +func (h *PlaybookHandler) getPlaybooksAutoComplete(w http.ResponseWriter, r *http.Request) {
You're right! Fixed in https://github.com/mattermost/mattermost-plugin-incident-management/pull/358/commits/bc7d032c8d4ea75ae8551aebf22ef19ebbcc95d4

2020-11-04 17:39 UTC, agarciamontoro commented
I know now why the E2E tests are failing only in CI (we have an environment variable overriding the server config). I'm waiting on some configuration we need to do in CircleCI itself, but consider it fixed!

2020-11-04 18:14 UTC, crspeller approved these changes

2020-11-13 15:22 UTC, cpoile approved these changes
Nice work Alejandro -- this is fiddly stuff to code, but super useful, thanks!

2020-11-13 15:22 UTC, cpoile commented on server/command/command.go
> +			"All incident data will be lost. To self-test, type `/incident test self CONFIRM SELF-TEST`")
maybe:

```suggestion
			"All incident data will be lost. To self-test, type `/incident test self CONFIRM TEST SELF`")
```

along with the change the check would require above

2020-11-13 15:22 UTC, cpoile commented on server/command/command.go
> +	if !r.pluginAPI.User.HasPermissionTo(r.args.UserId, model.PERMISSION_MANAGE_SYSTEM) {
Will Murat, Stuart, Paul, etc have system admin privileges when they run the test command?

2020-11-13 15:22 UTC, cpoile commented on server/command/command.go
> +var fakeCompanyNames = []string{
nice. :)

2020-11-13 15:22 UTC, cpoile commented on server/command/command.go
> +var incidentNames = []string{
Did you write these? Nice job

2020-11-13 15:45 UTC, agarciamontoro commented on server/command/command.go
> +	if !r.pluginAPI.User.HasPermissionTo(r.args.UserId, model.PERMISSION_MANAGE_SYSTEM) {
I was assuming that, but maybe it's not true. @muratbayan @sadohert, will you have system admin privileges when running this command to generate the data?

2020-11-13 15:46 UTC, agarciamontoro commented on server/command/command.go
> +var incidentNames = []string{
Yes! It was fun :joy:

2020-11-13 15:47 UTC, agarciamontoro commented on server/command/command.go
> +			"All incident data will be lost. To self-test, type `/incident test self CONFIRM SELF-TEST`")
It makes it more consistent, thanks for the suggestion!

2020-11-13 16:05 UTC, agarciamontoro commented on server/command/command.go
> +			"All incident data will be lost. To self-test, type `/incident test self CONFIRM SELF-TEST`")
Done in https://github.com/mattermost/mattermost-plugin-incident-management/pull/358/commits/8e7adeb91db64c6c7da27e29f94ff891bf5bddaf

2020-11-16 18:03 UTC, agarciamontoro commented on server/command/command.go
> +	if !r.pluginAPI.User.HasPermissionTo(r.args.UserId, model.PERMISSION_MANAGE_SYSTEM) {
Confirmed offline that they will have system admin privileges when they run the test command.

2020-11-20 17:07 UTC, muratbayan approved these changes
Reviewed today with Alejandro as I don't have a local setup, the behaviour is great.
Approved

2020-11-20 18:11 UTC, agarciamontoro commented
@sadohert are you ok with merging this?

2020-11-23 12:58 UTC, sadohert commented
I'm good to merge this.  Functionality looks great!

Probably doesn't need to block this PR, but as discussed in the channel, I was having an issue with a simple `make` of the plugin.  `make deploy` got me up and running in my local dev environment (after make noticed I didn't have my environment details setup correctly and notified me).
![image](https://user-images.githubusercontent.com/260544/99963831-5ddff200-2d60-11eb-85c1-145325a9f53a.png)

2020-11-23 12:59 UTC, sadohert approved these changes
I didn't review code.  Only tested the functionality with:
```
/incident test bulk-data 10 3 2020-01-31 2020-11-22 2
```

AND
```
/incident test create-incident 6utgh6qg7p8ndeef9edc583cpc 2020-11-23 PR-Testing
```

And I surfed around to check out what was produced.  Nice job!

2020-11-23 13:03 UTC, agarciamontoro commented
@justinegeffen is it ok if I merge this PR? Or do you want to complete the docs before?

2020-11-23 13:07 UTC, justinegeffen commented
@agarciamontoro, I am working on the docs at the moment so you can go ahead and merge. :)

2020-11-23 13:07 UTC, agarciamontoro commented
/update-branch

2020-11-23 14:47 UTC, merged