Update telemetry.md
mattermost/mattermost-plugin-incident-management pull request #360
Opened 2020-10-27 20:43 UTC by justinegeffen

- Updating telemetry content for https://github.com/mattermost/mattermost-plugin-incident-response/pull/359. 
- Ideally mirror the structure of the Mattermost telemetry docs for consistency.

2020-10-27 21:16 UTC, cpoile commented on docs/telemetry.md
>  - `type`: Type of the event. It always contains the string `track`.
this needs a bit of an update -- `type` is three types, and then `action` are those in the #359 PR notes

2020-10-28 14:15 UTC, justinegeffen commented on docs/telemetry.md
> +## Incident data
@cpoile, before I continue in this vein, I wanted to get your thoughts as to whether it's more scalable than the previous table. And also whether I've understood it correctly.

2020-10-30 13:22 UTC, justinegeffen commented
@cpoile, following up on this as I'd like to merge it today. Any feedback on the structure would be great. :)

2020-10-30 18:11 UTC, justinegeffen commented
@cpoile, could you let me know if the proposed structure for the events/properties works?

I wasn't sure whether the event would be called ``CreateIncident`` or ``actionCreate`` (for example).

2020-10-30 20:05 UTC, cpoile requested changes
I rewrote the intro to be a bit more explanatory--please edit as you see fit (or throw it out). :)

As for the event metadata: I think this is an easier way of presenting the information. I changed the events to reflect what we're collecting. It might be easies to just accept the suggestions, and then I'll probably have to go through and do another edit because it's difficult to edit this way. 

Thanks Justine!

2020-10-30 20:05 UTC, cpoile commented on docs/telemetry.md
> +## Event data
I think we can delete everything below here

2020-11-02 18:38 UTC, amyblais commented on docs/telemetry.md
> +- `TeamID`: Unique identifier of the team where the incident channel is created
```suggestion
- `TeamID`: Unique identifier of the team where the incident channel is created.
```

2020-11-02 18:38 UTC, amyblais commented on docs/telemetry.md
> +- `Public`: True if the incident was public, false if it was private.
Some of the "true" and "false" words throughout the bullet points are formatted with an in-line code, others are not.

2020-11-02 19:03 UTC, cpoile approved these changes
One more change, otherwise looks great, thanks Justine!

2020-11-02 19:03 UTC, cpoile commented on docs/telemetry.md
> +- `NewState`: If the task was marked uncompleted. If the task was marked completed, the result will be `done`.
```suggestion
- `NewState`: `null` if the task is uncompleted, `done` if the task was marked completed.
```

2020-11-02 19:34 UTC, merged