MM-29706 - update status dialog; recent update post
mattermost/mattermost-plugin-incident-management pull request #374
Opened 2020-11-02 23:31 UTC by cpoile

#### Summary
- Next piece of the status RHS epic
- `/incident status`, or clicking on the footer button, opens the dialog:
![image](https://user-images.githubusercontent.com/1490756/97930230-e3135080-1d38-11eb-9581-99286a9d129d.png)
- filling out the message and pressing `Update Status` will post it to the channel:
![image](https://user-images.githubusercontent.com/1490756/97930275-fd4d2e80-1d38-11eb-8d21-66534f63f50b.png)
- The status posts are kept in a list in the incident. Not in a separate table, that's overkill since we never have to query based on postID -- just joined together and pulled apart with `strings.Fields` when saving/loading from the store.
- When we're handling displaying the most recent non-deleted status in the RHS, and the finding the "last updated status" time, we'll go through the list of status postIDs backwards (most recent first) and use the first non-deleted post (if any).

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-29706

2020-11-03 11:34 UTC, agarciamontoro requested changes
This is really cool, thank you! :tada: I left some suggestions below, only one thing blocking for the permissions.
I agree with your opinion on the tests, btw, let's wait for having the whole thing to add proper E2E tests.

2020-11-03 11:34 UTC, agarciamontoro commented on server/incident/service.go
> +}
I think we should check the permissions here: if I'm logged in as a valid Mattermost user and I send a POST request to the `/incidents/{id}/update-status-dialog` endpoint, this function will be directly called. As I can send the request to any incident ID, this would let me update the status in any incident, regardless of my membership to the channel. (If I'm not missing something here)

2020-11-03 11:34 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec("ALTER TABLE IR_Incident ADD StatusPostsIDsString VARCHAR(4096) DEFAULT ''"); err != nil {
This would fit 151 post IDs, right? I'd say that this is enough for normal incidents, but I don't know if we should increase it for incidents that have a high frequency of status updates, and for those more rare incidents that last more time (or that are restarted).

2020-11-03 11:34 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +		StatusPostsIDsString: strings.Join(origIncident.StatusPostsIDs, " "),
Nit: our IDs are always 26 characters long. Maybe we can concatenate them all together?

2020-11-03 19:56 UTC, cpoile commented on server/api/incidents.go
> +	incidentRouterAuthorized.HandleFunc("/update-status-dialog", handler.updateStatusDialog).Methods(http.MethodPost)
Yah, personally I think we don't need to document them --- not because of the work (as you say, I can cut and paste most of this) but because we're advertising something that isn't officially part of the public API. That's my 1/5 on it. :)

2020-11-03 19:56 UTC, cpoile commented on server/command/command.go
> +		}
You could also make an execute command call to the API -- which, come to think of it, means we have to double check that we're doing permissions checks on all of our command functions...

2020-11-03 19:56 UTC, cpoile commented on server/command/command.go
> +	}
Same answer as above :)

2020-11-03 19:56 UTC, cpoile commented on server/incident/incident.go
> +	StatusPostsIDs []string             `json:"status_posts_ids"`
Nice catch! Thanks!

2020-11-03 19:56 UTC, cpoile commented on server/incident/service.go
> +}
Ahhh, now I remember why I didn't check edit permissions here -- they're checked in the router. :)
I should be checking post permissions though, thanks for reminding me about that.

2020-11-03 19:57 UTC, cpoile commented on server/sqlstore/incident.go
> +		StatusPostsIDsString: strings.Join(origIncident.StatusPostsIDs, " "),
Yah, screw it, I'm just changing it to being text for both dbs. I'm tired of MySQL's "optimizations" :)

2020-11-03 20:04 UTC, cpoile commented on server/sqlstore/incident.go
> +		StatusPostsIDsString: strings.Join(origIncident.StatusPostsIDs, " "),
nvm, mysql can't have default values for text columns.

2020-11-03 20:05 UTC, cpoile commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec("ALTER TABLE IR_Incident ADD StatusPostsIDsString VARCHAR(4096) DEFAULT ''"); err != nil {
Expanded to 8192 -- 303 updates should be enough... :)

2020-11-03 20:07 UTC, cpoile commented on server/sqlstore/incident.go
> +		StatusPostsIDsString: strings.Join(origIncident.StatusPostsIDs, " "),
About concatenating -- I think using the join with a space and splitting with fields is less error-prone.

2020-11-04 04:39 UTC, itao reviewed
Let's use `/incident update` instead of `/incident status`. It's a verb that implies user is going to do a thing, whereas status reads kind of ambiguous whether it's fetching info or posting.

This may not be part of this PR, but just in case: the `status`, `message`, and `reminder` fields in the modal should default to the previous value rather than blank values.

2020-11-04 11:16 UTC, agarciamontoro commented on server/api/incidents.go
> +	incidentRouterAuthorized.HandleFunc("/update-status-dialog", handler.updateStatusDialog).Methods(http.MethodPost)
Sounds good!

2020-11-04 11:18 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +		StatusPostsIDsString: strings.Join(origIncident.StatusPostsIDs, " "),
Sounds good!

2020-11-04 11:21 UTC, agarciamontoro commented on server/incident/service.go
> +}
Nice, thanks!

2020-11-04 11:41 UTC, agarciamontoro approved these changes
Great, thanks for addressing my comments! :tada:

2020-11-04 15:47 UTC, crspeller requested changes

2020-11-04 15:47 UTC, crspeller commented on server/command/command.go
> +		}
Actually are these checks not redundant since this path just opens the dialog? It doesn't actually perform any action. Maybe leave these off and just check when the action is performed?

2020-11-04 15:47 UTC, crspeller commented on server/command/command.go
> +		}
Also even if we want these, I think the "edit incident" check is redundant given the can post to channel below. It's not clear, but edit incident checks read and can post checks write.

2020-11-09 14:41 UTC, agarciamontoro commented on server/incident/service.go
> +	postID, err := s.poster.PostMessage(incidentToModify.ChannelID, options.Message)
@christopher.poile: any reason why it is the bot who posts the update, instead of the user that created it? I just realized that this is in conflict with the mocks, that show the user being the author of the update posts.

2020-11-12 11:12 UTC, agarciamontoro commented on server/incident/service.go
> +	postID, err := s.poster.PostMessage(incidentToModify.ChannelID, options.Message)
While doing the E2E tests for the update status feature, I realized that this is probably a must. Otherwise, regular users won't be able to edit/delete updates. (Up until now, I was always logged in as sysadmin, so I could edit/delete any post)

2020-11-14 16:38 UTC, cpoile commented on server/command/command.go
> +		}
Good point, I removed the can post check -- I think we should still have the edit incident/incident member check (the update dialog will have the previous update text pre-filled in, and we don't want to send that to just anyone).

2020-11-14 16:40 UTC, cpoile commented on server/incident/service.go
> +	postID, err := s.poster.PostMessage(incidentToModify.ChannelID, options.Message)
Good question -- given the recent meeting we had about the status update, this will be posted as the user in the incident channel.

2020-11-14 17:03 UTC, cpoile commented
I'm leaving the status update post styling for another ticket (https://mattermost.atlassian.net/browse/MM-30551), since that scope has changed and the rest of our PRs are based on this one.

2020-11-17 17:44 UTC, crspeller approved these changes

2020-11-17 19:25 UTC, merged