MM-29771 - Reminder for next update
mattermost/mattermost-plugin-incident-management pull request #379
Opened 2020-11-16 21:28 UTC by cpoile

#### Summary
- (not a problem for release) Depends on: https://github.com/mattermost/mattermost-plugin-api/pull/79 for the reminder scheduling.
- (might be a problem) Depends on https://github.com/mattermost/mattermost-server/pull/16286 to allow clicking on the `Update Status` button to open the update status dialog on the client. It works on webapp and mobile. This will require, 5.30? Can @lieut-data confirm?
- The reminder looks like (ignore the bot badge):
![image](https://user-images.githubusercontent.com/1490756/99309923-36e96380-2828-11eb-9279-d176d1b93d54.png)
- Clicking `Dismiss` will delete the post. Clicking `Update Status` will bring up the update status dialog (mobile and desktop)
- Posting an update (no matter how it's done--clicking the button, clicking Update Status in the RHS, typing the `/incident update` slash command) will delete the post.
- If a new update is posted before the pending reminder has expired, the pending reminder is removed. There will never be two reminders active for the same incident.
- For now, there’s no way to remove a pending reminder, other than making a new update with a “none” reminder.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-29711

2020-11-17 15:49 UTC, crspeller commented
@cpoile No idea why we added that check. From the goimports docs: `put imports beginning with this string after 3rd-party packages; comma-separated list`. So it just changes the order of the imports. 
Not sure why it was erroring, but removing it is fine by me.

2020-11-18 03:05 UTC, lieut-data requested changes
Neat stuff! A few comments below.

2020-11-18 03:05 UTC, lieut-data commented on server/incident/reminder.go
> +	if _, err = s.scheduler.ScheduleOnce(key, time.Now().Add(timeInMinutes*time.Minute)); err != nil {
Should we only `ScheduleOnce` after we've saved the `ReminderID`?

2020-11-18 03:05 UTC, lieut-data commented on server/incident/reminder.go
> +	key := model.NewId()
Do we need a unique `key` all the time? Could we just use the `IncidentID`, given there's only one reminder at play per incident?

2020-11-18 03:05 UTC, lieut-data commented on server/incident/reminder.go
> +	err := s.pluginAPI.KV.Get(reminderPrefix+key, &reminder)
It's slightly unfortunate that we have to maintain two KV store entries here: one managed by the new `cluster` code, and another to keep the `IncidentID` around. See below for question on just using the `IncidentID` as the key, but also wondering why we aren't just querying the database for the incident with `ReminderId == key`? Is that because it's in the props bag?

2020-11-18 11:14 UTC, agarciamontoro requested changes
This is great, Christopher! Thank you :tada: 

I left some minor comments below.

2020-11-18 11:14 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_list_view.tsx
> +        const post = getPostFromState(postId);
Hm that's a good point. I tested it with recent posts and it worked, but I did not tests with old posts outside of the loaded ones. I bet those are not in the store :/

2020-11-19 01:17 UTC, cpoile commented on server/api/incidents.go
> +	incidentID, err := h.incidentService.GetIncidentIDForChannel(requestData.ChannelId)
Thanks, fixed.

2020-11-19 01:17 UTC, cpoile commented on server/api/incidents.go
> +	ReturnJSON(w, map[string]interface{}{"trigger_id": triggerID}, http.StatusOK)
This fixes https://mattermost.atlassian.net/browse/MM-30544 (see: 7d88b34) - it passes the slash command's trigger_id to the client so we can set it.
I updated the api.yaml (though I'm not totally sure this needs to be public? It's a response only needed by internal code.) @agarciamontoro can you take a look to see that I made the yaml change correctly? Thanks!

2020-11-19 01:18 UTC, cpoile commented on server/incident/incident.go
> +	JSONBag
Yep, that's a good idea. Done.
--update: moot with the new SQL

2020-11-19 01:18 UTC, cpoile commented on server/incident/incident.go
> +// Incident struct, add it to the migrations and the store select/insert/update statements, and the
I think we would have to go through each incident, unmarshal the PropsJSON, set the new column, and set the updated PropsJSON. Like we did with the data migration code. Not trivial, but doable. I added that description to the comments. 

IMO, I think this would be rare--we would have to have originally thought that the new field would never need to be searched on/ordered by, and then realized that it does. I think the ease of using Props outweighs the rare case of needing to graduate a field.

-- edit after offline discussion: looks like we should move it all into SQL. :)

2020-11-19 01:18 UTC, cpoile commented on server/incident/incident.go
> +	ReminderInMinutes int
Yah, that makes sense (it will also fix the comments below). Reminder will be a `time.Duration`, rather than an `int64`, just to make it clearer what it is.

2020-11-19 01:18 UTC, cpoile commented on server/incident/service.go
> +		if err = s.SetReminder(incidentID, time.Duration(options.ReminderInMinutes)); err != nil {
It's fixed now to be clearer.

2020-11-19 01:19 UTC, cpoile commented on server/sqlstore/migrations.go
> +				Where(sq.Eq{"JSONBag": nil})
With a complete nil, squirrel fails reading into `*json.RawMessage`, so we need to have something in there. I chose `"{}"` but I think `""` or `"null"` would probably work, since you can unmarshal that into the Props struct.

-- edit: moot after changing to full-on SQL. Except there's a similar migration I had to do for the new column. nil leads to a sql error.

2020-11-19 01:20 UTC, cpoile commented on webapp/src/components/rhs/rhs_list_view.tsx
> +        const post = getPostFromState(postId);
I made the change; had to make a `RHSListIncident` component (because of the async call to get the post from the server). I think there are ways to improve this if we're concerned about efficiency (fetch all posts at once), but that's probably premature.

There is one issue though -- it won't update when a post is deleted. It's because this branch doesn't have the message update hook that alejandro's building in another PR. I'll have to fix this later this week: https://mattermost.atlassian.net/browse/MM-30787

-- update: there's a new issue, the entire webapp (and especially our components in the RHS) update on every key press in the center channel's post input. It's brutal. Not sure if it's something I've done, but it's realllllly bad. Will have to look into it tomorrow.

2020-11-19 01:20 UTC, cpoile commented on webapp/src/components/duration.tsx
> +    const start = moment(props.from);
Done!

2020-11-19 01:21 UTC, cpoile commented on server/incident/reminder.go
> +	if _, err = s.scheduler.ScheduleOnce(key, time.Now().Add(timeInMinutes*time.Minute)); err != nil {
Right, in case the save fails or the job fires immediately (I don't think that's possible since it spawns a go routine, and that won't preempt the current goroutine... but just in case)

2020-11-19 01:21 UTC, cpoile commented on server/incident/reminder.go
> +	key := model.NewId()
Right, that makes sense -- didn't think of that. Nice.

2020-11-19 01:21 UTC, cpoile commented on server/incident/reminder.go
> +	err := s.pluginAPI.KV.Get(reminderPrefix+key, &reminder)
Yep, you're both right on the money. Good idea, making that change.

2020-11-19 01:21 UTC, cpoile commented on server/api/incidents.go
> +		HandleError(w, errors.New("reminderButtonUpdate failed to find incidentID"))
Right, good catch, removed. (I hadn't updated to the new error handlers, but it's there now.)

2020-11-19 01:21 UTC, cpoile commented on server/api/incidents.go
> +	ReturnJSON(w, nil, http.StatusOK)
Yes, the internal do plugin request expects a response, not just the code, it will error without it.

2020-11-19 01:21 UTC, cpoile commented on server/bot/poster.go
> +	}
Yes, good call. I think I meant to do that then forgot. Thanks!

2020-11-19 01:21 UTC, cpoile commented on server/incident/reminder.go
> +	}
It doesn't matter now, because this code is gone, but: if this key was never deleted then yah, I think it would live forever.

2020-11-19 13:19 UTC, lieut-data commented on server/incident/reminder.go
> +	if _, err = s.scheduler.ScheduleOnce(key, time.Now().Add(timeInMinutes*time.Minute)); err != nil {
Yeah, my primary concern was about the save failing. Though your second case is, I think, still possible: there are multiple underlying threads and it's perfectly possible for another goroutine to start and run to completion while this one is still active and finishing up. No pre-emption required.

2020-11-23 17:18 UTC, cpoile commented on webapp/src/components/rhs/rhs_list_view.tsx
> +        const post = getPostFromState(postId);
fixed

2020-11-23 17:25 UTC, cpoile commented
Everything is good to go now -- the new StatusPosts is in there, and.

@agarciamontoro see the `lastUpdatedByIncidentId` in the selectors for an example of how we could make a selector that returns a map of the current "most recent status update postIDs". (for #377) 
It's returning a map because then we only have to compute that map once (when the `myIncidentsByTeam` changes). Nice and simple.

2020-11-23 18:27 UTC, agarciamontoro approved these changes
Looks great! I left some questions below, but nothing blocking.

Thank you :tada:

2020-11-23 18:27 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	}
I'm not entirely sure I understand why we need to delete any rows in this table. When creating a new incident, the incident ID should not exist in this table, and when updating it, we should only add posts, not delete them (they are soft deleted with delete_at != 0). But maybe I'm missing something here?

2020-11-23 18:27 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +						PostID VARCHAR(26) NOT NULL,
Do we need a reference to the `Posts` table here? I recall that there may be performance concerns with that, right?

2020-11-23 18:27 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +					CREATE TABLE IF NOT EXISTS IR_StatusPosts (
Should we add a unique constraint on both columns here, as in the table in postgres?

2020-11-23 18:27 UTC, agarciamontoro commented on server/incident/incident.go
> +	StatusPosts    []StatusPost         `json:"status_posts"`
Why do we need both?

2020-11-23 18:27 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	//    ORDER BY p.CreateAt;
Old commented code?

2020-11-23 18:27 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	//subclause := queryForIncidentIDs.Prefix("ir.IncidentID IN (").Suffix(")")
Old commented code? (and some lines below, too)

2020-11-23 18:27 UTC, agarciamontoro commented on server/api/incidents.go
> +	ReturnJSON(w, map[string]interface{}{"trigger_id": triggerID}, http.StatusOK)
Looks good to me! (I had missed this comment before)

2020-11-23 18:28 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	//subclause := queryForIncidentIDs.Prefix("ir.IncidentID IN (").Suffix(")")
This is outdated, sorry (I reviewed commit by commit)

2020-11-23 18:29 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	}
(This says it's outdated because I reviewed it in an older commit, but the question is still the same for the newer code)

2020-11-23 19:19 UTC, cpoile commented on server/sqlstore/incident.go
> +	}
It's true, we'll probably never delete status posts, because we'll probably never save an incident that has removed an id from `incident.StatusPostIDs`. But I didn't want to make it impossible to do so, you know?

2020-11-23 19:19 UTC, cpoile commented on server/sqlstore/migrations.go
> +						PostID VARCHAR(26) NOT NULL,
Good question! Personally I don't think we'll gain anything from a reference here, and it feels wrong to me to introduce a constraint on the `Posts` table because we don't 'own' it. If we have that constraint, and then the server wants to delete or change an ID, they might get an error and not understand that it's our plugin that's causing it. What do you think @lieut-data ?

2020-11-23 19:19 UTC, cpoile commented on server/sqlstore/migrations.go
> +					CREATE TABLE IF NOT EXISTS IR_StatusPosts (
Ah, good catch, missed that.

2020-11-23 19:25 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +						PostID VARCHAR(26) NOT NULL,
Us not owning it is a good enough point for me.

2020-11-23 19:26 UTC, agarciamontoro commented on server/incident/incident.go
> +	StatusPosts    []StatusPost         `json:"status_posts"`
We already have that data in the frontend with each element in `StatusPosts` having the ID :thinking:

2020-11-23 19:27 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	}
I cannot think of a use case where we want to do that, and maybe this hides it in case we do it by mistake? Hm, I'm not sure.

2020-11-23 19:30 UTC, cpoile commented on server/incident/incident.go
> +	StatusPosts    []StatusPost         `json:"status_posts"`
Right, but we only save the `StatusPostIDs` to the db, and the rest of the server code will only append to `StatusPostIDs` (e.g., `service/UpdateStatus(...)`) --- so we still need it. The frontend will probably only use `StatusPosts`. I guess it's unfortunate that we have a part of the incident struct (`StatusPosts`) that is only used on the frontend.

2020-11-23 19:33 UTC, agarciamontoro commented on server/incident/incident.go
> +	StatusPosts    []StatusPost         `json:"status_posts"`
Yeah, you're right. We may need to decouple the server struct from the frontend struct sometime in the future (not for this PR, I'm not asking for more changes here)

2020-11-23 19:35 UTC, cpoile commented on server/sqlstore/incident.go
> +	}
Okay, I can remove the code -- we can add it later if we find we need it. 😄 
Done in 6dbf430

2020-11-23 20:53 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +	}
Oh great, thanks!

2020-11-23 21:11 UTC, lieut-data approved these changes
Really great work moving this into the database, @cpoile -- a handful of comments below, but I think they aren't strictly blocking.

2020-11-23 21:11 UTC, lieut-data commented on server/sqlstore/incident.go
> +		asIncident, err2 := s.toIncident(rawIncident)
nit: pre-declare `asIncident` instead of `err2`?

2020-11-23 21:11 UTC, lieut-data commented on server/sqlstore/incident.go
> +	tx, err := s.store.db.Beginx()
Is the transaction necessary here? (It's read-only, and if we're looking for an isolation level, I think we have to be explicit.)

2020-11-23 21:11 UTC, lieut-data commented on server/sqlstore/incident.go
> +    SELECT ?, ? FROM DUAL
Can we avoid `FROM DUAL` and the database-specific query? Is it necessary?

2020-11-23 21:11 UTC, lieut-data commented on server/sqlstore/migrations.go
> +						DO
nit: can we unindent this somewhat?

2020-11-23 21:11 UTC, lieut-data commented on server/sqlstore/migrations.go
> +						PostID VARCHAR(26) NOT NULL,
Definitely don't want a foreign key on `Posts` -- that can creates locks on the `Posts` table when inserting into this table and dramatically kill performance for the rest of the app. (Foreign keys ~= bad for high-volume tables)

2020-11-23 21:11 UTC, lieut-data commented on server/sqlstore/migrations.go
> +				Set("ReminderPostID", "").
Instead of forcing a write to the table, would it make sense to guard our read code to `COALESCE(ReminderPostId, "")` instead, guaranteeing the code will never break for a future `NULL` value (i.e. if someone clears it out incorrectly or some such).

A practical situation where this might occur is if the plugin gets downgraded for some reason, and then later upgraded again -- records created in the interim won't have a non-NULL value.

2020-11-23 22:28 UTC, cpoile commented on server/incident/incident.go
> +	newIncident.StatusPostIDs = newStatusPostsIDs
Yah, I had tried that before, but remember when we were having trouble with nil slices vs empty slices in the tests? `require.Equal` says they're different. But, regardless of what the test package says, we wanted to make sure every call to sqlstore returns the consistent type -- remember we decided on nil (however, we check for nil and return an empty array in the api layer, because the frontend chokes on a nil array). 

So, long story short, this is here so that `sqlstore/CreateIncident` (which calls clone) returns a nil slice. If we use the `append([]string{}` version, `CreateIncident` will return an empty slice, and a lot of the tests fail.

Same thing for `[]StatusPost` just below it. :)

2020-11-23 22:28 UTC, cpoile commented on server/sqlstore/incident.go
> +		asIncident, err2 := s.toIncident(rawIncident)
Yep! But I'm 0/5 on the extra line vs the `err2`; both are a little ugly to me. 🤷

2020-11-23 22:29 UTC, cpoile commented on server/sqlstore/incident.go
>      );`
Yep, old MySQL versions need this, I discovered.

2020-11-23 22:29 UTC, cpoile commented on server/sqlstore/incident.go
> +	tx, err := s.store.db.Beginx()
Right, I guess it's okay to not use a transaction. The reason for it was to make sure the statusPosts query was seeing the same version as the previous queries. But since we're using statusPosts as append-only, I guess it's okay to not use it. 

Just for my own education, @lieut-data is there a better way to ensure a consistent version across 2 or more queries?

2020-11-23 22:29 UTC, cpoile commented on server/sqlstore/incident.go
> +    SELECT ?, ? FROM DUAL
Yep, old MySQL needs this.

2020-11-23 22:29 UTC, cpoile commented on server/sqlstore/migrations.go
> +						DO
Whoa, don't know why it looks like that on github, it was much more reasonable in the ide. Will fix.

2020-11-23 22:29 UTC, cpoile commented on server/sqlstore/migrations.go
> +				Set("ReminderPostID", "").
That's a good solution, thanks! I learned something new today. :)
Just a note -- sqlx won't be able to map a function to a field, so you have to put the field name next to the function.

2020-11-23 23:02 UTC, merged

2020-11-24 14:16 UTC, lieut-data commented on server/incident/incident.go
> +	newIncident.StatusPostIDs = newStatusPostsIDs
I admit I don't remember the specific conversation, but ideally we could shift complexity to the tests here. For example, if `require.Equal` doesn't work for us, let's write a wrapper that handles `len(slice) == 0` specially. 

The only other touchpoint was how the REST API responds, but that's a "rendering" concern that definitely shouldn't be handled in the store.

2020-11-24 14:19 UTC, lieut-data commented on server/sqlstore/incident.go
> +	tx, err := s.store.db.Beginx()
A transaction is the right way to do this, but it quickly gets into the weeds as to which isolation level to use and what's actually supported by the database in question, etc. I sometimes find that seeing an "inconsistent" view may not actually matter, so long as there isn't a surprise coupling between the two queries. In this case, seeing a slightly older set of status posts (or seeing a newer one) /shouldn't/ break anything, I think?

2020-11-24 14:21 UTC, cpoile commented on server/incident/incident.go
> +	newIncident.StatusPostIDs = newStatusPostsIDs
Right, I agree that we should make the tests not distinguish between them. But IMO, I think it's probably more important that the various sqlstore methods are returning the same empty type, and not returning a `[]string(nil)` and a `[]string{}` for the same field depending on what method you're calling.

2020-11-24 14:26 UTC, cpoile commented on server/sqlstore/incident.go
> +	tx, err := s.store.db.Beginx()
I don't /think/ it will break anything, but I left it in just in case -- I'd rather be safe and correct, and taking out the transaction felt a bit like premature optimization. I figure we can take it out if we see it causing any problems.

2020-11-24 14:42 UTC, lieut-data commented on server/incident/incident.go
> +	newIncident.StatusPostIDs = newStatusPostsIDs
Right, but in `Go`, `[]string(nil)` and `[]string{}` are semantically the same type, and it should not be necessary to distinguish them. The "oddities" are at the edge cases here.