#15761
mattermost/mattermost-plugin-incident-management pull request #384
Opened 2020-11-20 21:53 UTC by SBagaria2710

- Close popover on clicking outside the description

#### Summary

#### Ticket Link

2020-11-20 21:53 UTC, mattermod commented
Hello @SBagaria2710,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-11-20 21:54 UTC, lieut-data commented
Thanks, @SBagaria2710! I've asked our team to help review your changes :)

2020-11-23 12:29 UTC, agarciamontoro requested changes
Thank you for your contribution, @SBagaria2710 :tada: Your idea of using that hook is great, we only need to use the correct reference, as I describe below.

2020-11-23 12:29 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +    useClickOutsideRef(target, () => {
This `target` references the info icon, used by the `Overlay` component to place the popover: see how it's declared as `ref` in the `InfoIcon` component and used as the `target` field in the `Overlay component`. So the effect this has right now is that clicking anywhere outside the info icon (included the popover itself) will close the popover.

What we should do instead is create a second reference with `useRef` and use it in the `StyledPopover` component itself. You may need to create a `div` container wrapping everything inside the `StyledPopover` component, so you can add this new reference as its `ref`.

2020-11-23 12:29 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +
Minor thing: the linter is complaining that there is some blank space here. Could you remove it? Thanks!

2020-11-23 16:04 UTC, agarciamontoro commented
/check-cla

2020-12-02 18:07 UTC, SBagaria2710 reviewed
I made the required changes. It seems to be working fine now.

2020-12-03 09:45 UTC, SBagaria2710 commented on webapp/src/components/checklist_item.tsx
> +    useClickOutsideRef(target, () => {
Made the required changes. Also, it seems to be working fine in local.
Let me know if any other changes are required from my end.

2020-12-03 10:02 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +    useClickOutsideRef(target, () => {
> Now what happens is when I click on the info-icon, popover won't close once opened. What is happening here is that after triggering the handler function of the useClickOutsideRef, it is triggering the onClick set at InfoIcon. How do we overcome this behaviour?

I'd say it's ok to keep the popup open when the user clicks on the info icon. We have an X button and clicking outside of it would close it, so I'd say it's a good solution.

2020-12-03 10:03 UTC, agarciamontoro approved these changes
Looks good, thank you! :tada: I left a non-blocking comment below.

2020-12-03 10:03 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
Why do we need the timeout here? Can we remove it?

2020-12-03 10:15 UTC, SBagaria2710 commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
Like I mentioned above, on `useClickOutsideRef` it is working as expected, but then it is triggering the `onClick` on the `InfoIcon`.

Which is why I put the `useClickOutsideRef`  as a callback for `setTimeout` so that it trigger the `onClick` prior to `useClickOutsideRef`.

I don't think it'll be a problem, but I am open to learn about the alternative if you'd want to get into this.

2020-12-03 10:20 UTC, SBagaria2710 commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
Also, I made this change as I felt it wasn't a good user experience. I'd expect to click on the same button/icon to toggle.
I can remove it tho if you want 👍

2020-12-03 10:35 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
I'm thinking now that another solution for this would be to change the current `useClickOutsideRef` hook to `useClickOutsideRefs`, and pass a list of refs instead of a single one. In the code of the hook, check that none of the refs is being clicked on. In the caller code, use it simply with `useClickOutsideRef([popoverRef, target], setShowTooltip(false))`.
I have not tested it, but it may work. Are you open to try it?

2020-12-03 15:53 UTC, SBagaria2710 commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
I don't see any harm in trying. Let me raise another PR in sometime :)

2020-12-04 19:42 UTC, cpoile commented
/update-branch

2020-12-04 20:00 UTC, cpoile requested changes
Looks great @SBagaria2710 ! One more thing then we're good to go.

2020-12-04 20:00 UTC, cpoile commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
I agree -- I don't think we need it. You can probably do:
```suggestion
        setShowTooltip(false);
```

2020-12-04 20:36 UTC, SBagaria2710 commented on webapp/src/components/checklist_item.tsx
> +        setTimeout(() => setShowTooltip(false), 10);
So, do we want to try `useClickOutsideRefs` which @agarciamontoro  suggested? Or should I just remote `setTimeout` and update the PR?

2020-12-07 14:30 UTC, cpoile approved these changes
Thanks for the contribution @SBagaria2710, looks great!

2020-12-07 14:31 UTC, cpoile commented
@prapti I've tested it on my own machine, but would feel better if you could build from this branch and test on your own machine. It's your call if you think this can make the code freeze deadline (I would vote yes, if it passes your testing). Thanks!

2020-12-07 19:58 UTC, prapti approved these changes
Tested locally and on cloud and can verify that the descriptions no longer overlap each other. This is a great improvement. Thank you @SBagaria2710 for working on this fix!

Thanks for the heads up @cpoile! I too think this one should make the code freeze deadline :)

2020-12-08 22:30 UTC, merged

2020-12-09 11:22 UTC, SBagaria2710 commented
Thank you all @lieut-data  @agarciamontoro  @cpoile @prapti ! 🙇 

This was my **first contribution** to mattermost. Looking forward to making more in near future 😄  🚀 

Until next time...