MM30518 Adding preferences tab to playbook edit.
mattermost/mattermost-plugin-incident-management pull request #388
Opened 2020-11-24 20:17 UTC by crspeller

#### Summary
Adds preferences tab to playbook edit. Preferences page is just a placeholder. 
Also changed the titles in the "Permissions" sidebar to their new names. 

Screenshot:
![image](https://user-images.githubusercontent.com/3191642/100146076-30717200-2e4e-11eb-8468-f4c0d56b12dc.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30518

2020-11-24 20:29 UTC, cpoile approved these changes
Wow, that's amazingly concise. I love it.

2020-11-24 20:29 UTC, cpoile commented on webapp/src/components/tabs.tsx
> +        </>
Do we need the fragment here? It should know that `props.children[props.currentTab]` will return a ReactNode, right?

2020-11-24 20:29 UTC, cpoile commented on webapp/src/components/backstage/playbook_edit.tsx
> +                            {'TODO MM-30519 implment perferences.'}
```suggestion
                            {'TODO MM-30519 implement perferences.'}
```
😛

2020-11-24 20:30 UTC, crspeller commented on webapp/src/components/tabs.tsx
> +        </>
For some reason typescript wants it.

2020-11-25 11:23 UTC, agarciamontoro approved these changes
Nice and clean! :tada:

2020-11-25 11:25 UTC, agarciamontoro requested changes
Oopsie, just saw a couple of typos!

2020-11-25 11:25 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit.tsx
> +                            {'Perferences'}
```suggestion
                            {'Preferences'}
```

2020-11-25 11:25 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit.tsx
> +                            {'TODO MM-30519 implement perferences.'}
This is gone soon, but:
```suggestion
                            {'TODO MM-30519 implement preferences.'}
```

2020-11-25 15:12 UTC, agarciamontoro approved these changes
:tada:

2020-11-25 15:32 UTC, itao approved these changes
Looks great!

2020-11-25 15:33 UTC, merged