MM-28969] Enabled open RHS with incident list when issuing /incident list from webapp
mattermost/mattermost-plugin-incident-management pull request #412
Opened 2020-12-10 22:56 UTC by shuang2411

#### Summary
Added a new if statement to catch '/incident list' at the client side of the webapp

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/16403

2020-12-10 22:56 UTC, mattermod commented
Hello @shuang2411,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-12-14 11:06 UTC, agarciamontoro requested changes
Thank you for your contribution, @shuang2411, the code looks great! :tada:

We can still improve the behavior in a couple of cases:
- when the RHS is already open, it looks like nothing has happened. To inform the user, we can simply send an ephemeral post stating something like "The list of your incidents is already open in the RHS".
- there is also an edge case I had not anticipated: we can be in an incident channel and have the RHS open, but its state may be `ViewingIncident`. To overcome this, I think that once the RHS is open, `setRHSViewingList` can do the trick, but I have not tested it.

Could you try these two things and see if they work? Thank you!

2020-12-15 18:28 UTC, agarciamontoro requested changes
We're almost there! Thank you, @shuang2411 :tada:

I left a couple of comments below, mostly related to the changes in other files we probably don't need. But I also discovered an edge case while testing your changes:

If the user is in an incident channel, and the RHS is closed, executing `/incident list` opens the RHS, but shows the incident details instead of the list. I think that this happens because the default when the RHS opens in an incident channel is to view the incident details, so that's the one shown. Even if we later dispatch the `setRHSViewingList`, I think that we are probably competing with the `setRHSViewingIncident` action dispatched [here](https://github.com/mattermost/mattermost-plugin-incident-management/blob/master/webapp/src/components/rhs/rhs_main.tsx#L36) :thinking: I cannot think of a sensible way to solve this without modifying the main behaviour of the RHSMain component. Any idea on this, @lieut-data?

2020-12-15 18:39 UTC, shuang2411 commented on tests-e2e/package.json
> +    "cypress": "^4.1.0",
No, I do not think this is needed. It must be added unintentionally when I try to install cypress.

2020-12-15 18:44 UTC, shuang2411 commented
> We're almost there! Thank you, @shuang2411 🎉
> 
> I left a couple of comments below, mostly related to the changes in other files we probably don't need. But I also discovered an edge case while testing your changes:
> 
> If the user is in an incident channel, and the RHS is closed, executing `/incident list` opens the RHS, but shows the incident details instead of the list. I think that this happens because the default when the RHS opens in an incident channel is to view the incident details, so that's the one shown. Even if we later dispatch the `setRHSViewingList`, I think that we are probably competing with the `setRHSViewingIncident` action dispatched [here](https://github.com/mattermost/mattermost-plugin-incident-management/blob/master/webapp/src/components/rhs/rhs_main.tsx#L36) 🤔 I cannot think of a sensible way to solve this without modifying the main behaviour of the RHSMain component. Any idea on this, @lieut-data?

@agarciamontoro 
Thank you for your feedback!
I think you are right. All the changes you commented are not necessary. Sorry, I should have kept my working tree clean.

2020-12-15 18:49 UTC, shuang2411 reviewed
@agarciamontoro 
Thank you for your feedback!
I think you are right. All the changes besides the first one are not necessary. Sorry, I should have kept my working tree clean. 

Btw, is their any thing I need to do from my end? I am new to open source. Please definitely let me know if there is anything I can do!

2020-12-16 17:55 UTC, agarciamontoro commented
Hi @shuang2411! You can simply add a new commit reverting those changes. For example, removing the files not needed, commiting that and pushing again. Ping me in Mattermost if you need any more help with it!

2020-12-18 11:03 UTC, agarciamontoro requested changes
This looks great, @shuang2411! :tada:

I just left a comment on a change in package-lock.json that is still there, but otherwise, it is ready! :tada:

Jesse and I talked about the concern I had about this edge case where `/incident list` opens the incident details in an incident channel with the RHS closed. Solving that is not trivial, and it will be a bit more involved, so we can merge this PR as it is (after removing the change in package-lock.json) and I will create another ticket to address that specific problem, so we can tackle it afterwards. If you're open to continue contributing, please feel free to take it (I'll link to it here in this PR when I create it)!

2020-12-18 11:06 UTC, agarciamontoro commented on webapp/package-lock.json
> +        "custom-protocol-detection": "github:ismailhabib/custom-protocol-detection#e51da5c97d37d4ea04d872fb48467d793e7741ea",
This is the change we need to remove.

2020-12-18 14:57 UTC, lieut-data approved these changes
Looks great -- thanks @shuang2411!

2020-12-18 15:02 UTC, agarciamontoro approved these changes
Woohoo! Thank you, @shuang2411, and sorry for all the back and forth in this!

Let's move into the QA process so the PR can get merged. There is no need for you to do anything else for the moment, unless QA requests some changes! :tada:

2020-12-18 15:06 UTC, shuang2411 commented
@agarciamontoro Thank you so much!! Thank you for all your helps during the process!

2020-12-18 15:09 UTC, agarciamontoro commented
@prapti, heads-up that this PR covers most of the functionality expected in the ticket, except for one edge case that has been postponed for a future ticket: if the user is in an incident channel, and the RHS is closed, `/incident list` shows the incident details instead of the incident list. We'll fix this in https://mattermost.atlassian.net/browse/MM-31484.

2020-12-19 02:29 UTC, prapti requested changes
Thank you for your work on this PR @shuang2411!
The improvement in the functionality of the command works great on the webapp, and still works as expected in mobile apps.
The only suggestion I have is to show the message `The list of your incidents is already open in the right hand side of the channel` when the RHS is already showing the incident list. Or perhaps getting rid of the work "already" so that it does not read strange when issuing the command when RHS is not open or open with a different view.
Other than that, I think it's great.

2020-12-20 21:52 UTC, shuang2411 commented
> Thank you for your work on this PR @shuang2411!
> The improvement in the functionality of the command works great on the webapp, and still works as expected in mobile apps.
> The only suggestion I have is to show the message `The list of your incidents is already open in the right hand side of the channel` when the RHS is already showing the incident list. Or perhaps getting rid of the work "already" so that it does not read strange when issuing the command when RHS is not open or open with a different view.
> Other than that, I think it's great.

Hi @prapti,
I think I have already implemented the function you suggested.
An ephemeral post will appear after you input `/incident list`.
Is this what you want?
![image](https://user-images.githubusercontent.com/44971432/102725232-4fdfab80-42e3-11eb-977d-ae69be48a649.png)

If you some how does not see this, can you let me know how to reproduce it? Thank you!

2020-12-22 02:24 UTC, prapti reviewed
Hi @shuang2411, yeah removing "already" should be fine in my opinion. However, wondering if you've pushed the change after removing it? I'm still seeing the older ephemeral message.

2020-12-22 02:24 UTC, prapti commented on server/command/command.go
> +		r.postCommandResponse("The list of your incidents is already open in the right hand side of the channel.")
```suggestion
		r.postCommandResponse("The list of your incidents is open in the right hand side of the channel.")
```

2020-12-22 02:26 UTC, shuang2411 commented on server/command/command.go
> +		r.postCommandResponse("The list of your incidents is already open in the right hand side of the channel.")
I have not pushed yet. I just want to make such the ephemeral post is working fine for you. I will push now!

2020-12-22 02:35 UTC, shuang2411 commented on server/command/command.go
> +		r.postCommandResponse("The list of your incidents is already open in the right hand side of the channel.")
@prapti Please review the latest commit！

2020-12-22 18:16 UTC, prapti approved these changes
This is awesome! Thank you for your contribution @shuang2411 and really appreciate your patience through the PR review. Your changes are going in to the Incident Management product 🎉

2020-12-22 18:18 UTC, prapti commented
@agarciamontoro This one is ready for merge (I think you're the only dev available who can merge this, so TIA!) 😄

2020-12-23 11:10 UTC, agarciamontoro commented
Thank you, @prapti!

And thank you for the contribution @shuang2411 :tada: It's awesome :)

2020-12-23 11:10 UTC, merged