MM-31919: set id when rendering Textbox
mattermost/mattermost-plugin-incident-management pull request #428
Opened 2021-01-14 14:46 UTC by lieut-data

#### Summary
The `Textbox` component from webapp requires an `id`, throwing an exception in development environments when we validate props at runtime.

This doesn't appear in a cloud/production environment, where runtime prop checking is disabled, and thus must be verified locally.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-31919

2021-01-14 14:53 UTC, agarciamontoro commented
It looks like the linter does not find the import :thinking:

2021-01-14 14:55 UTC, lieut-data commented
Oops! Looks like I might be relying on the implicit presence of `lodash` from internal dependencies. I'll find a replacement instead.

2021-01-18 14:36 UTC, lieut-data commented
I've replaced the lodash import with a trivial implementation of my own that should suffice. Sorry for the thrashing!

2021-01-18 15:50 UTC, crspeller requested changes

2021-01-18 15:50 UTC, crspeller commented on webapp/src/components/backstage/step_edit.tsx
> +    const [id] = useState(uniqueId('step-command-'));
This will actually call `uniqueId` every render, incrementing the idCounter as a side effect. The result will be ignored though. See: https://reactjs.org/docs/hooks-reference.html#lazy-initial-state

Also it would be nice and clean if you make a custom hook like `useUniqueID` and used that. That way all the implementation details like the call to `uniqueId` having to be in a callback and the destructuring of id can be hidden.

2021-01-18 15:55 UTC, lieut-data commented on webapp/src/components/backstage/step_edit.tsx
> +    const [id] = useState(uniqueId('step-command-'));
Ooh, good catch! Will create a custom hook instead -- thanks :)

2021-01-18 18:57 UTC, crspeller approved these changes

2021-01-19 08:52 UTC, agarciamontoro approved these changes
Nice! :tada:

2021-01-20 02:31 UTC, prapti approved these changes
The "Failed prop type" error no longer appears when creating a playbook with the "Incident Management" template.
LGTM!

2021-01-20 13:44 UTC, merged