MM-31636 Add status field
mattermost/mattermost-plugin-incident-management pull request #429
Opened 2021-01-14 15:25 UTC by crspeller

#### Summary
Adds a status field to incidents.
Status is updated at the same time that the status updates feature is used. 
The statuses are:
- Reported
- Active
- Resolved
- Archived

A follow up ticket will make Archived status actually archive the channel. 

Note: Still working on cypress tests. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31636

2021-01-14 20:23 UTC, cpoile requested changes
Nice! A few minor questions, one bigger concern (the tests indicate `LastResolvedAt` might not be working the way I expected it to work)

2021-01-14 20:23 UTC, cpoile commented on server/incident/service.go
>  		status = "Ended"
This seems like it should be changed, too? (for line 224 below, in the new `service.go`)

2021-01-14 20:23 UTC, cpoile commented on server/sqlstore/migrations.go
> +				if err := addColumnToMySQLTable(e, "IR_Incident", "CurrentStatus", "TEXT NOT NULL"); err != nil {
I think you have MySql and Postgres reversed here

2021-01-15 11:15 UTC, agarciamontoro requested changes
Cool! :tada: Below are mostly nits, but there are also a couple of things that got me a bit confused (I think in the same sense than Chris' comment).

Also, a couple of general questions:
- Are the CreateAt, EndAt and DeleteAt columns from the IR_Incident deprecated? Should we document this somewhere else than in the code handling it? In a comment in the migrations or somewhere else?
- Should we automatically select the `Active` status in the interactive dialog when clicking on the "Reopen Incident" button?

2021-01-15 11:15 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_title.tsx
> +                        isActive={incident && incidentIsActive((incident))}
Are these double parentheses a typo or some kind of trick I don't know?

2021-01-15 11:15 UTC, agarciamontoro commented on server/sqlstore/incident_test.go
> +		/*{
Should we delete this test? And the other three that are commented out?

2021-01-15 20:54 UTC, cpoile commented on server/incident/service.go
> +		return errors.Wrap(err, "failed to write status post to store. There is now insconsistant state.")
Are you sure we want to remove the transaction and then have this chance of inconsistent state?

2021-01-15 21:31 UTC, crspeller commented on server/api/incidents.go
> -	}
Removing the validation here because it's not necessary to validate the status string. Invalid just gives no results. 
But I do remember I need to change the client side of this as well. Will do.

2021-01-15 21:32 UTC, crspeller commented on server/incident/incident.go
> +const (
0/5 I just put it with the other status stuff.

2021-01-15 21:32 UTC, crspeller commented on server/incident/incident.go
>  // client; it is not saved to the db.
Nope. Wasn't true before this PR ether.

2021-01-15 21:33 UTC, crspeller commented on server/incident/incident_test.go
> +		},
Yes it does. If it didn't, it would be inconsistent with the updates presented.

2021-01-15 21:36 UTC, crspeller commented on server/incident/incident_test.go
> +			expected: 123,
Nope 123 is correct. If you make multiple status updates with "Resolved" the actual resolution time is the first one, not the last one. 

I changed the test to have CreateAt for the first post to be 1. But the function does assume the DB has ordered these correctly, so that discrepancy is not caught.

2021-01-15 21:37 UTC, crspeller commented on server/incident/incident_test.go
> +			expected: 456,
Same as above.

2021-01-15 21:39 UTC, crspeller commented on server/incident/service.go
>  		status = "Ended"
Yup. Good catch.

2021-01-15 21:41 UTC, crspeller commented on server/sqlstore/migrations.go
> +				if err := addColumnToMySQLTable(e, "IR_Incident", "CurrentStatus", "TEXT NOT NULL"); err != nil {
Good catch!

2021-01-15 21:44 UTC, crspeller commented on server/incident/incident.go
> +	}
Not the last, but the first. I think the function name might be confusing. Going to change it to just `ResolvedAt()`

2021-01-15 21:47 UTC, crspeller commented on server/command/command.go
> +	r.actionUpdate()
That's a great idea! https://mattermost.atlassian.net/browse/MM-32100

2021-01-15 21:50 UTC, crspeller commented on server/api/incidents.go
> -
Well it is redundant since we won't persist a given EndAt anyway. But the truth is I accidentally started removing EndAt before realizing what a core that would be.  I think we might want to clean it up and actually remove it later. Ok to keep this gone since it's redundant?

2021-01-15 21:56 UTC, crspeller commented on server/incident/service.go
> +		return errors.Wrap(err, "failed to write status post to store. There is now insconsistant state.")
What transaction? The only ones I removed had only one DB call in them?

2021-01-15 21:58 UTC, crspeller commented on webapp/src/components/rhs/rhs_footer.tsx
> +}
The less components we have hooked to redux, the better. This pattern is used by other components we have.

2021-01-15 21:59 UTC, crspeller commented on webapp/src/components/rhs/rhs_title.tsx
> +                        isActive={incident && incidentIsActive((incident))}
It's an amazing trick that gets you to comment on my PRs 😆

2021-01-15 22:00 UTC, crspeller commented on server/sqlstore/incident_test.go
> +		/*{
Done.

2021-01-19 13:51 UTC, cpoile commented on server/incident/incident_test.go
> +		},
What happens on the front end when the user deletes a status post? Is the incident's status updated?

2021-01-19 15:28 UTC, crspeller commented on server/incident/incident_test.go
> +		},
Yes it is.

2021-01-21 09:26 UTC, agarciamontoro commented on server/api/incidents.go
> -
Oh yeah that's true, thanks for the clarification!

2021-01-21 09:28 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_footer.tsx
> +}
Ok to leave this as it is now, no problem. Simply to continue the discussion on this:

> The less components we have hooked to redux, the better

Why? I understand why we would want to keep our writes to the store to a minimum, but I don't see a problem in reading it from several places, as it is our source of truth. I wanna hear your thoughts on this!

2021-01-21 09:36 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_title.tsx
> +                        isActive={incident && incidentIsActive((incident))}
Interesting, I guess that the parentheses are simply treated as a grouping operator. I checked and you could have written `incidentIsActive(((((incident)))))`, it would still work. Maybe we can use that to emphasize some pieces of code that we find very very important :joy:

2021-01-21 12:32 UTC, agarciamontoro requested changes
Thanks for the effort with the E2E tests, I see that you had some fun with them :joy:

I left some comments about tests being removed/commented out, and some other nits. Other than that, the only remaining "concern" I have is the one pointed out by @cpoile: from a user perspective, I'd find confusing that deleting a message changes the status.

2021-01-21 12:32 UTC, agarciamontoro commented on server/incident/incident.go
> +	}
Oh you're going backwards, that's right. What if the incident was reopened?

2021-01-21 12:32 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +			"CurrentStatus":           rawIncident.CurrentStatus(), // Added to make querying easier
How would it be more difficult without this?

2021-01-21 12:32 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/slash_command/test_spec.js
> -                it('creates an incident with the correct date in the past', () => {
Why is this one deleted?

2021-01-21 12:32 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_rhs_list_spec.js
> +        /*it('when user has no active incidents', () => {
There are multiple commented tests in this file. Should we uncomment them?

2021-01-21 12:32 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_creation_spec.js
> -        it('while viewing a group message channel', () => {
Why are all these tests in this file deleted?

2021-01-21 12:32 UTC, agarciamontoro commented on tests-e2e/cypress/integration/backstage/incident_list_spec.js
> -        it('by status', () => {
We can no longer filter by status?

2021-01-21 12:32 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
> -// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Why are we getting rid of these tests?

2021-01-21 12:36 UTC, agarciamontoro commented on tests-e2e/cypress/integration/backstage/incident_list_spec.js
> -        it('by status', () => {
I saw that we can, but we only have the Ongoing and Ended status. Is this planned for a future PR?

2021-01-21 15:09 UTC, cpoile commented
Re: the e2e tests, do you want to wait a bit while we try to change the docker image we're using to run the tests? That might fix some of these.

@crspeller how hard would it be to put back the tests for now? I tried doing it last night by reverting the commits, but I think I broke something by accident. If you put the tests back, I can test to see if changing the docker image will fix the weird failures. I would rather do that than remove e2e tests that /should/ be working.

2021-01-21 15:49 UTC, crspeller commented on server/incident/incident.go
> +	}
It will consider the total time from when the incident was first opened. I feel like that's the right time to consider because you should only be reopening in the case of a mistake, or the incident was not actually solved.

2021-01-21 15:53 UTC, crspeller commented on webapp/src/components/rhs/rhs_footer.tsx
> +}
The more connections you have to redux:
- The less portable your components are to share with other projects.
- Gives you less flexibility in re-use. What if I want to show an incident that's not the current one?
- Performance penalty for every connection. Redux has to notify every connected component of the change and that component has to do its did anything change check. 
- The less testable your components are. (not that we really test our components, but given our troubles with e2e testing, maybe more component testing and less e2e would be nice)

2021-01-21 15:53 UTC, crspeller commented on server/api/api.yaml
>            example: active
It's not case sensitive.

2021-01-21 15:56 UTC, crspeller commented on server/sqlstore/incident.go
> +			"CurrentStatus":           rawIncident.CurrentStatus(), // Added to make querying easier
Every time we read the incident we would have to do a query on the status posts table to fill this in. Not totally sure which one would be better.

2021-01-21 16:00 UTC, crspeller commented
@agarciamontoro @cpoile To answer your questions on why I killed a bunch of tests, it's because I couldn't for the life of me get them working. (see my sanity level slowly dropping in my commit messages)

I have already spent way too much time on them and just want to get this PR in so I can stop blocking people.

2021-01-22 15:11 UTC, cpoile commented
#434 is in!

2021-01-29 14:24 UTC, cpoile approved these changes
Hooray! :tada:

2021-01-29 15:23 UTC, agarciamontoro approved these changes
Great job, Christophers, thank you both! :)

2021-02-01 02:01 UTC, prapti commented
In test queue.

2021-02-01 19:49 UTC, prapti commented
So nice to see the status field pop up in the status update form :)

@crspeller @lieut-data I have one concern though that might be worth considering before merging, and please let me know if this has already been addressed before with any decision: with these changes, the incidents that were already ended with prior plugin versions show up as "Ongoing", however they can be filtered as "Resolved" in the backstage; and the ones resolved after this PR show as "Ended". This will cause confusion for the incidents that were supposed to be ended.

2021-02-01 20:02 UTC, crspeller commented
@prapti That's not great. Let me take a look. I think I might have screwed up the migration in my flailing over the e2e tests.

2021-02-01 21:37 UTC, crspeller commented
@prapti Latest commit should fix the upgrade issue.

2021-02-01 22:57 UTC, prapti approved these changes
Tested in local and cloud test servers. The issue of ended incidents showing up as 'Ongoing' is fixed with the latest commit.
Approving. Will add more edge cases in the test plan for later upgrades.

2021-02-01 23:40 UTC, merged