MM-32148 - Generate version metadata from tags
mattermost/mattermost-plugin-incident-management pull request #433
Opened 2021-01-21 19:28 UTC by cpoile

#### Summary
- If the current commit has a tag, use that as the version (without the prefix 'v'). Otherwise, use the latest tag and add the short hash, eg. "1.2.0+9fcd0b92".
- Q: should we also update the `release_notes_url` in `plugin.json`?
- I think this should work even if you don't run a `make` command before pushing the PR... But then the `plugin.json` in the main directory won't have the up-to-date version, but the bundle should.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-32148

2021-01-21 20:08 UTC, cpoile commented
Doing some experimentation with e2e tests, will request reviews when that's all over with

2021-01-22 16:57 UTC, lieut-data requested changes
Nice! A few comments below.

2021-01-22 16:57 UTC, lieut-data commented on build/setup.mk
> +BUILD_TAG_LATEST = $(shell git describe --tags --abbrev=0)
Ooh, I haven't encountered `git describe` before. Should we leverage `--match v*` to match only version tags?

2021-01-22 16:57 UTC, lieut-data commented on plugin.json
> +    "version": "1.2.0+9fcd0b92",
Propose we remove the `version` attribute from the checked-in file otherwise we'll always have a permanently old version checked in.

2021-01-22 16:57 UTC, lieut-data commented on server/manifest.go
> +  "version": "1.2.0+9fcd0b92",
Should we remove these files from the repo, and let them get generated only at build time? (Do we also `.gitignore` them?)

2021-01-22 16:57 UTC, lieut-data commented on build/setup.mk
> +LDFLAGS += -X "main.BuildTagCurrent=$(BUILD_TAG_CURRENT)"
nit: LDFLAGS seems like it might "have side effects" for downstream invocations. Should we inline these instead?

2021-01-22 18:02 UTC, cpoile commented on build/setup.mk
> +BUILD_TAG_LATEST = $(shell git describe --tags --abbrev=0)
Nice, added!

2021-01-22 18:03 UTC, cpoile commented on plugin.json
> +    "version": "1.2.0+9fcd0b92",
I tried to do that, but couldn't think of a way to do that--manifest will output the whole plugin.json, including the `version` field

2021-01-22 18:04 UTC, cpoile commented on server/manifest.go
> +  "version": "1.2.0+9fcd0b92",
I was thinking of that, but then we would have to have the "base" `plugin.json` somewhere, so that we can read it in. I was thinking of putting it in the build directory. What do you think?

2021-01-22 18:04 UTC, cpoile commented on build/setup.mk
> +LDFLAGS += -X "main.BuildTagCurrent=$(BUILD_TAG_CURRENT)"
Sure, will do.

2021-01-22 18:17 UTC, cpoile commented on server/manifest.go
> +  "version": "1.2.0+9fcd0b92",
I made that change so we can see what it looks like. It's not perfect though, because we still update the manifest files with the version info, and I can't think of a way to not have to check that in. Maybe ignore the manifest files as well since they're generated?   Hmm, let's see if that will work.

2021-01-22 18:21 UTC, cpoile commented on server/manifest.go
> +  "version": "1.2.0+9fcd0b92",
There, I think that works. Now the three generated files are not checked in. Only thing that feels a little "wrong" is putting the base `plugin.json` file in the build directory. Open to alternatives there. But if we keep it in the root directory it will be updated and we will start to check in old version numbers.

2021-01-22 18:55 UTC, lieut-data commented on plugin.json
> +    "version": "1.2.0+9fcd0b92",
Can we just manually edit the file in this PR to remove the `version` attribute? I guess then the `manifest` will always leave a modified `plugin.json` in the repo... which would be annoying. Can we write the output to a temporary `plugin.json` (i.e. the one that's being put into the bundle path)?

2021-01-22 18:56 UTC, lieut-data commented on server/manifest.go
> +  "version": "1.2.0+9fcd0b92",
Oops, commented above before I read this thread. Yeah, wondering if we can keep the `root` one the `base` one, and change `manifest` to write to the temporary one in the bundle directory at build time?

2021-01-22 18:57 UTC, cpoile commented on plugin.json
> +    "version": "1.2.0+9fcd0b92",
Yep, we can write the plugin.json anywhere, and change the bundle instructions.  Will do that.

2021-01-22 19:08 UTC, cpoile commented on plugin.json
> +    "version": "1.2.0+9fcd0b92",
There, the `plugin.json` is back in the root, but without the `version` field. The version field is generated and put into the build directory, and the make bundle copies that generated one to the dist folder. Looks good now, thanks!

2021-01-22 19:12 UTC, cpoile commented on server/manifest.go
> +  "version": "1.2.0+9fcd0b92",
As a compromise we're writing into the build directory, because we rm the dist directory before copying the manifest, and I don't want to mess around with that. :)

2021-01-22 21:12 UTC, cpoile commented
@lieut-data @crspeller ready for re-review, then we can start testing the cloud build process. :)(

2021-01-25 15:45 UTC, lieut-data requested changes
Thanks, @cpoile! One comment below about `build/plugin.json`.

2021-01-25 15:45 UTC, lieut-data commented on Makefile
> +MANIFEST_FILE ?= build/plugin.json
Hmm, this doesn't "smell right" to me -- at least from the context of reading the `Makefile`, `MANIFEST_FILE` is about defining the source of truth. This file doesn't exist yet: I'd love to see whatever temporary path we use be an implementation detail vs. something that's configured like this.

Maybe we just make pass the desired output path to `bin/manifest` and invoke it manually within the `bundle` target? Or, actually, "applying" `plugin.json` only needs to happen within the `bundle` target, so maybe it's just a different `bin/manifest apply_version` command or some such.

2021-01-25 16:08 UTC, cpoile commented on Makefile
> +MANIFEST_FILE ?= build/plugin.json
Yep, that does work better, nice idea. I added a `manifest dist` command to write the `plugin.json` to the dist directory. Thanks!

2021-01-25 16:11 UTC, lieut-data approved these changes
:tada:

2021-01-25 16:14 UTC, crspeller approved these changes
Awesome!

2021-01-25 16:14 UTC, crspeller commented on plugin.json
> +        "executable": ""
Why did this come back?

2021-01-25 16:17 UTC, cpoile commented on plugin.json
> +        "executable": ""
Looks like it was generated by marshalling the manifest struct. I can not check it in if it's causing confusion?

2021-01-25 16:32 UTC, crspeller commented on plugin.json
> +        "executable": ""
@cpoile Nope its fine.

2021-01-25 16:33 UTC, merged