MM-32246: fix welcome rhs as sysadmin
mattermost/mattermost-plugin-incident-management pull request #445
Opened 2021-02-01 16:54 UTC by lieut-data

#### Summary
The welcome RHS incorrectly prompted sysadmins to create an incident if there were /any/ playbooks in the team, regardless of whether the sysadmin was a member. Fix this by adding an optional `member_only` parameter to the query and use it when testing for playbooks.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-32246

2021-02-01 16:57 UTC, crspeller requested changes

2021-02-01 16:57 UTC, crspeller commented on tests-e2e/cypress/integration/frontstage/rhs/welcome_spec.js
> +describe('incident rhs > welcome', () => {
Does this really need an E2E test? Seems like your unit test covers this functionality.

2021-02-01 16:58 UTC, cpoile approved these changes

2021-02-01 18:12 UTC, crspeller approved these changes

2021-02-03 18:39 UTC, lieut-data commented
/update-branch

2021-02-04 03:52 UTC, prapti approved these changes
Welcome RHS for sysadmin is fixed.
Thank you for adding the e2e tests for the Welcome RHS Jesse!

2021-02-04 13:12 UTC, merged